# Vectorization Playground

This notebook explores vectorization techniques in NumPy and demonstrates why vectorized operations are much faster than explicit loops in Python.

In [20]:
import numpy as np
import time

## 1. Vectorization vs. Loops: Basic Comparison

Let's compare the time it takes to compute a dot product using a loop vs. vectorized operations.

In [21]:
# Create two large arrays
n = 1000000
a = np.random.rand(n)
b = np.random.rand(n)

print(f"Array size: {n:,} elements")

Array size: 1,000,000 elements


In [22]:
# Non-vectorized: Using a loop
tic = time.time()
c = 0
for i in range(n):
    c += a[i] * b[i]
toc = time.time()

print(f"Loop version: {(toc - tic) * 1000:.4f} ms")
print(f"Result: {c}")

Loop version: 232.7070 ms
Result: 250080.4348665423


In [23]:
# Vectorized: Using np.dot
tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(f"Vectorized version: {(toc - tic) * 1000:.4f} ms")
print(f"Result: {c}")

Vectorized version: 0.3388 ms
Result: 250080.43486655277


## 2. Element-wise Operations

NumPy allows element-wise operations without explicit loops.

In [24]:
# Element-wise operations
x = np.array([1, 2, 3, 4, 5])

print(f"x = {x}")
print(f"x + 10 = {x + 10}")
print(f"x * 2 = {x * 2}")
print(f"x ** 2 = {x ** 2}")
print(f"np.exp(x) = {np.exp(x)}")
print(f"np.log(x) = {np.log(x)}")

x = [1 2 3 4 5]
x + 10 = [11 12 13 14 15]
x * 2 = [ 2  4  6  8 10]
x ** 2 = [ 1  4  9 16 25]
np.exp(x) = [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
np.log(x) = [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [25]:
from cmath import exp


n = 100
v = np.random.randn(n)
u = np.exp(v)
print(v, u)

[-0.07575384 -0.34349368  0.45745259 -1.27639856  0.17889611  0.13493007
 -1.12970835 -0.6356903  -0.50539802  0.11577613 -1.24908315 -0.40623406
  0.29858009  0.28747232 -2.11111171  0.25937711  1.16130615  0.46549105
 -1.34215654  2.08485904 -0.9062398  -0.17395595 -0.22549031  0.2730542
 -0.24622205  1.5429527   1.45863227 -1.23546325  0.22476176 -0.46802918
  0.10316063  0.47112283 -1.26441385 -0.45425907  0.01549235 -0.16651998
 -0.81331733  0.92781531 -0.41066423 -0.86245936 -1.4197603  -1.39760975
  0.46015591 -1.72155799 -1.72430156 -0.75327286 -0.93203014 -0.92328177
 -1.20215112 -2.1898285  -0.23509776 -0.78738459 -0.78119585  1.1013543
 -0.77695836 -1.15009446 -1.25153007  0.76285689  0.65143788  1.20560075
 -0.52692236  1.53916212  0.19534271  0.38255033 -0.95270947  1.07223557
  0.09694003  0.05070935 -0.76575006  0.9798144   0.89801406  0.49006344
 -0.37869961  0.28989946  0.06122682  0.8460036  -0.1753925   0.04532349
  0.87520967 -1.41035715  0.52924727  1.76101886  0.7

In [26]:
## Vectorizing Logicstic Regression


## 3. Broadcasting

Broadcasting allows NumPy to work with arrays of different shapes.

In [27]:
# Broadcasting example
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([10, 20, 30])

print("Matrix A:")
print(A)
print(f"\nVector b: {b}")
print("\nA + b (broadcasting):")
print(A + b)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector b: [10 20 30]

A + b (broadcasting):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [28]:
# Column broadcasting
c = np.array([[100], [200], [300]])

print("Column vector c:")
print(c)
print("\nA + c (column broadcasting):")
print(A + c)

Column vector c:
[[100]
 [200]
 [300]]

A + c (column broadcasting):
[[101 102 103]
 [204 205 206]
 [307 308 309]]


## 4. Matrix Operations

Common matrix operations used in deep learning.

In [29]:
# Matrix multiplication
X = np.random.randn(3, 4)  # 3x4 matrix
W = np.random.randn(4, 5)  # 4x5 matrix

print(f"X shape: {X.shape}")
print(f"W shape: {W.shape}")

# Matrix multiplication
Z = np.dot(X, W)  # or X @ W
print(f"Z = X @ W shape: {Z.shape}")

X shape: (3, 4)
W shape: (4, 5)
Z = X @ W shape: (3, 5)


In [30]:
# Transpose
print("X:")
print(X)
print("\nX.T (transpose):")
print(X.T)
print(f"\nX.T shape: {X.T.shape}")

X:
[[-0.01900263  0.33724908 -0.95401045  0.16017793]
 [-1.3240375   1.12692071 -1.8682802   1.86336687]
 [-0.41141591 -0.70751159  0.37746758 -0.65417689]]

X.T (transpose):
[[-0.01900263 -1.3240375  -0.41141591]
 [ 0.33724908  1.12692071 -0.70751159]
 [-0.95401045 -1.8682802   0.37746758]
 [ 0.16017793  1.86336687 -0.65417689]]

X.T shape: (4, 3)


## 5. Activation Functions (Vectorized)

Implementing common activation functions using vectorization.

In [31]:
def sigmoid(z):
    """Vectorized sigmoid function"""
    return 1 / (1 + np.exp(-z))

def relu(z):
    """Vectorized ReLU function"""
    return np.maximum(0, z)

def tanh(z):
    """Vectorized tanh function"""
    return np.tanh(z)

# Test
z = np.array([-2, -1, 0, 1, 2])
print(f"z = {z}")
print(f"sigmoid(z) = {sigmoid(z)}")
print(f"relu(z) = {relu(z)}")
print(f"tanh(z) = {tanh(z)}")

z = [-2 -1  0  1  2]
sigmoid(z) = [0.11920292 0.26894142 0.5        0.73105858 0.88079708]
relu(z) = [0 0 0 1 2]
tanh(z) = [-0.96402758 -0.76159416  0.          0.76159416  0.96402758]


## 6. Softmax (Vectorized)

In [32]:
def softmax(z):
    """Vectorized softmax function"""
    exp_z = np.exp(z - np.max(z))  # Subtract max for numerical stability
    return exp_z / np.sum(exp_z)

# Test
z = np.array([1.0, 2.0, 3.0, 4.0])
print(f"z = {z}")
print(f"softmax(z) = {softmax(z)}")
print(f"Sum of softmax: {np.sum(softmax(z))}")

z = [1. 2. 3. 4.]
softmax(z) = [0.0320586  0.08714432 0.23688282 0.64391426]
Sum of softmax: 1.0


## 7. Your Playground

Experiment with your own vectorized operations below!

In [33]:
import numpy as np
# Broadcasting example
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
cal = A.sum(axis=0)
print (cal.reshape(1,3))
percentage = 100 * A/cal.reshape(1,3)
print (cal)
print (percentage)
print (A)

[[12 15 18]]
[12 15 18]
[[ 8.33333333 13.33333333 16.66666667]
 [33.33333333 33.33333333 33.33333333]
 [58.33333333 53.33333333 50.        ]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
a = np.random.randn(5)
print (a)
print (a.shape)
print (a.T)
print (a.T.shape)

b = np.random.randn(5,1)
print (b)
print (b.shape)
print (b.T)
print (b.T.shape)



[-0.07657626  1.62723158 -0.21996578 -0.2904491   0.31763542]
(5,)
[-0.07657626  1.62723158 -0.21996578 -0.2904491   0.31763542]
(5,)
[[ 0.82506003]
 [-0.87354891]
 [ 0.66732398]
 [ 0.31971271]
 [-0.82590636]]
(5, 1)
[[ 0.82506003 -0.87354891  0.66732398  0.31971271 -0.82590636]]
(1, 5)


In [35]:
a = np.random.randn(3, 1)
b = np.random.randn(2, 1)
print (a)
print (b)
print (a.shape)
print (b.shape)
# print (a+b)


c = np.random.randn(4, 3)
d = np.random.randn(1, 3)
e = c * d
print (e)
print (e.shape)








[[-0.04358178]
 [ 0.22453597]
 [-1.03263184]]
[[-0.14858805]
 [ 0.29250357]]
(3, 1)
(2, 1)
[[-1.11142876  0.15087757  0.59733094]
 [ 0.77325567 -0.37675671 -0.45253499]
 [ 1.11829832  0.52895432 -1.03372637]
 [ 0.08593259  0.23464724  1.30060319]]
(4, 3)


In [36]:
a = np.random.randn(5, 3)
b = np.random.randn(3, 2)
c = np.dot(a, b)
print (c)
print (c.shape)







[[-3.83456527 -2.49600233]
 [-1.11500823 -0.3934144 ]
 [ 1.85781922  1.30718051]
 [ 1.14434235  0.51763274]
 [-2.89464286  0.55394213]]
(5, 2)


In [39]:
a = np.zeros((2,3))
print (a)
print (a.shape)





[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

num_px = 4
num_samples = 5
my_image = np.random.randn(num_px, num_px, 3)
# print (my_image)
# print (my_image.shape)
image_vector = my_image.reshape(num_px*num_px*3, 1)
print (image_vector.shape)
X = np.random.rand(image_vector.shape[0], num_samples)
w = np.random.randn(image_vector.shape[0], 1)
b = 0.0
# print (X)
print (X.shape)
# print (w)
print (w.shape)
# print (b)

m = X.shape[1]
A = sigmoid(np.dot(w.T, X) + b)
cost = -1/m * np.sum(Y*np.log(A) + (1-Y)*np.log(1-A))
print (A.T)
print (A.T.shape)

dw = np.dot(X, (A-Y).T)/m
db = np.sum(A-Y)/m
















(48, 1)
(48, 5)
(48, 1)
[[0.86849593]
 [0.92828885]
 [0.95885798]
 [0.91253966]
 [0.79867635]]
(5, 1)


In [ ]:
def model(X_train, Y_train, X_test, Y_test, num_iterations=2000, learning_rate=0.5, print_cost=False):
    w, b = initialize_with_zeros(X_train.shape[0])
    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)
    w = parameters["w"]
    b = parameters["b"]

    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)
    
    if print_cost:
        print("Cost after iteration {}: {}".format(num_iterations, costs[-1]))
        

In [2]:
import numpy as np

A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True) 
print (B)
print (B.shape)





[[-0.70478734]
 [-0.1796125 ]
 [ 2.75846234]
 [ 2.63732653]]
(4, 1)
